@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false
skinparam actorStyle hollow

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor Black
}

skinparam rectangle{
    BorderColor Purple
}

title Auction Management Case Diagram

left to right direction

actor "System User" as SystemUser
actor "Client" as Client

rectangle "Use Cases" as usecases{
    rectangle "System User - Item" as SysUserItemUC {

        usecase "UC01 - Get all items" as UC01
        SystemUser --> UC01

        usecase "UC02 - Get an item by ID" as UC02
        SystemUser --> UC02

        usecase "UC03 - Register a new item" as UC03
        SystemUser --> UC03

        usecase "UC04 - Update an item" as UC04
        SystemUser --> UC04

        usecase "UC05 - Delete an item" as UC05
        SystemUser --> UC05
    }

    rectangle "System User - Category" as SysUserCategUC {

        usecase "UC06 - Get all categories" as UC06
        SystemUser --> UC06

        usecase "UC07 - Get a category by ID" as UC07
        SystemUser --> UC07

        usecase "UC08 - Register a new category" as UC08
        SystemUser --> UC08

        usecase "UC09 - Update a category" as UC09
        SystemUser --> UC09

        usecase "UC011 - Delete a category" as UC011
        SystemUser --> UC011
    }

    rectangle "System User - Sale" as userSaleUC {

        usecase "UC12 - Get all sales" as UC12
        SystemUser --> UC12

        usecase "UC13 - Get a sale by ID" as UC13
        SystemUser --> UC13

        usecase "UC15 - Update a sale" as UC15
        SystemUser --> UC15
    }

    rectangle "Client - Sale" as clientSaleUC {

        usecase "UC16 - Get all sales made by the client" as UC16
        Client --> UC16

        usecase "UC17 - Get a sale by ID (if the sale was made by the client)" as UC17
        Client --> UC17

        usecase "UC18 - Register a new sale" as UC18
        Client --> UC18
    }

}

@enduml